### ISSUE TITLE
couldn't get to run with npm version 4.6.2 or 8.1.2 but fresh install of yarn worked fine

### ISSUE THREAD

**Issue by JustinGOSSES** [johnnyqbui/Houston-Shelters#1]
couldn't get to "npm start" with npm version 4.6.2 or 8.1.2 but fresh install of yarn worked fine. Unclear what the issue was, but just flagging in case it wasn't some dumb set-up on my machine.

**Comment by colonelrascals** [comment]
Ran it on node 8.1.2 and npm 4.6.2 and it was fine. However, if I remember correctly early versions of node 8 were having problems with NPM closings (this is highlighted in node 8.1). node 8.2+ should be fine to work off. I will update the read me as needed.
