### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by kathruss** [johnnyqbui/Houston-Shelters#17]
Can we make the search function more broad so that a person can search a town name or their own address location and the map will take you to that location? As opposed to just being able to search shelters. It would also be nice to be able to search by need, like if someone has a bunch of dog food and are looking for a place to take it.

**Comment by jnolasco** [comment]
Absolutely, these are actually in progress right now! We have a rudimentary shelter search in place but we'd like to also make the "locate me" button a litte more functional as well as matching named needs like "dog food" etc.

**Comment by kathruss** [comment]
oops posted the wrong thing here. made a new issue for it instead. I think we need more than just the "locate me" feature to be able to locate a town or place - we've got lots of people working remotely and the locate me thing won't work for them. For example, I live in Oregon and was trying to find Refugio on your map to see if you have any shelters listed there (we do on our map) but was unable to

**Comment by jnolasco** [comment]
The needs are somewhat reliant on being categorized appropriately on the data collection side. We'll need to sit down with the data collection team to make sure that that is in progress, but it is certainly a thing we're hard at work trying to implement as a single map source. I'd link some prototype designs but I'm not sure I can link in this thread. We do hear you 100% though and you are absolutely right that this is what is needed going forward.

**Comment by johnnyqbui** [comment]
search function added to update
