### ISSUE TITLE
Timestamp readability

### ISSUE THREAD

**Issue by kathruss** [johnnyqbui/Houston-Shelters#19]
I love that there's an automated timestamp to show when a pin has been updated, but currently the format it's in makes it difficult for laypeople to read. Can it be adapted so that the time and date display either as the local time and date of the disaster area or as the local time and date of whoever is accessing the map? And have the format be more like 9/5/2017 11:45am CST

**Comment by johnnyqbui** [comment]
@kathruss Sure, will be updated in the next release.

**Comment by johnnyqbui** [comment]
resolved
