### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by johnnyqbui** [johnnyqbui/Houston-Shelters#23]
- [x] deep linking/routing. i.e. if someone types irmashelters.org/search/my+saerch+text+here and it matches one shelter, bring up that shelter

- [x] on initial page load: find shelther by ... my location | address | skip for now

- [x] rescue map?

- [x] ability to update shelters within the site

- [x] chat or message board

**Comment by jnolasco** [comment]
Will not implement rescue map. This is a wind event, local SAR can likely handle the few necessary rescues.
