### ISSUE TITLE
Add indicator of which filter is applied

### ISSUE THREAD

**Issue by ksmith6** [johnnyqbui/Houston-Shelters#3]
Inside `FilterMarker.js`, can you please update the `render` function to also include an indicator like a checkmark (or color-change) to show which filter is currently active?  It's unclear if the filters are exclusive or not since no UI feedback is provided upon clicking each filter.

**Comment by johnnyqbui** [comment]
Ok, I've updated it, how does it look? It's temporary for now, I will implement filter by checkboxes tomorrow.

**Comment by ksmith6** [comment]
I like that it shows the little border around the edges now.  However, the new colors (red, blue, purple, & green) are confusing.  I'd recommend just keeping all the colors the same and then apply a highlight color on hover events or upon click events to select that filter.

**Comment by johnnyqbui** [comment]
ok @ksmith6 , I've updated it. What do you think? Got a UX person to help out, so some things may change.

**Comment by ksmith6** [comment]
Looks great now- thanks for quick turnaround!
