### ISSUE TITLE
houston date format unreadable/invalid

### ISSUE THREAD

**Issue by jnolasco** [johnnyqbui/Houston-Shelters#47]
Click on a Houston shelter and none of the timestamps appear to be able to parse. Also breaks the "last 24 hours" filter.

**Comment by piperchester** [comment]
I can work on this 👍

**Comment by piperchester** [comment]
https://github.com/johnnyqbui/Houston-Shelters/pull/49

**Comment by johnnyqbui** [comment]
@piperchester sorry this issue has been resolved. I forgot to close it out. Thanks!
